"""Add email field to User model

Revision ID: 5ef51e90cb85
Revises: 61ac8843d5fb
Create Date: 2025-01-13 19:29:58.879426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef51e90cb85'
down_revision = '61ac8843d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])  # Added constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')  # Use the same constraint name here
        batch_op.drop_column('email')

    # ### end Alembic commands ###